### ISSUE TITLE
a connect.py problem in ZOC

### ISSUE THREAD

**Issue by eshujiushiwo** [ibuler/jumpserver#29]
when using zoc, always get this error.
the Character set is utf-8

```
Opt or ID>: p
Traceback (most recent call last):
  File "/opt/jumpserver/connect.py", line 806, in <module>
    main()
  File "/opt/jumpserver/connect.py", line 753, in main
    nav.search()
  File "/opt/jumpserver/connect.py", line 530, in search
    color_print('[%-3s] %-12s %-15s  %-5s  %-10s  %s' % ('ID', u'主机名', 'IP', u'端口', u'系统用户', u'备注'), 'title')
  File "/opt/jumpserver/connect.py", line 58, in color_print
    print msg
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-16: ordinal not in range(128) 
```

**Comment by eshujiushiwo** [comment]
```
Opt or ID>: p
[ID ] 主机名          IP               端口     系统用户        备注
[0  ] banwagong       xxxxx     xxxx  ['zhou']    

Opt or ID>: 0
Last login: Tue Dec 29 22:46:49 2015 from xxxx
Traceback (most recent call last):
  File "/opt/jumpserver/connect.py", line 806, in <module>
    main()
  File "/opt/jumpserver/connect.py", line 737, in main
    color_print(u'没有该用户，或许你是以root运行的 No that user.', exits=True)
  File "/opt/jumpserver/connect.py", line 58, in color_print
    print msg
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-17: ordinal not in range(128)
Opt or ID>: 

```

**Comment by ibuler** [comment]
我用zoc测试，没有复现，字符集问题。可以把 color_print(u'没有该用户，或许你是以root运行的 No that user.', exits=True) 中的 u去掉试试

**Comment by eshujiushiwo** [comment]
去掉u返回正常了。
```
没有该用户，或许你是以root运行的 No that user.
```
但是也是不能登陆跑jumpserver得这台机器么？

**Comment by ibuler** [comment]
查看 /etc/profile.d/zzjumpserver.sh就懂了

**Comment by eshujiushiwo** [comment]
我看到了，感谢啊。
另外这个问题我使用原生terminal连接的时候可以出现的。
zoc下面输入p都有问题。我再看看。

**Comment by eshujiushiwo** [comment]
zoc下，可以输入除了p以外的所有。我自己看下代码吧。谢谢了

```
Opt or ID>: h

###    欢迎使用Jumpserver开源跳板机系统   ###

        1) 输入 ID 直接登录.
        2) 输入 / + IP, 主机名 or 备注 搜索.
        3) 输入 P/p 显示您有权限的主机.
        4) 输入 G/g 显示您有权限的主机组.
        5) 输入 G/g + 组ID 显示该组下主机.
        6) 输入 E/e 批量执行命令.
        7) 输入 U/u 批量上传文件.
        8) 输入 D/d 批量下载文件.
        9) 输入 H/h 帮助.
        0) 输入 Q/q 退出.

Opt or ID>: d
进入批量下载模式
请输入主机名或ansile支持的pattern, 多个主机:分隔,q退出
Pattern>: q
Opt or ID>: g
[ID ] 组名               备注

Opt or ID>: p
Traceback (most recent call last):
  File "/opt/jumpserver/connect.py", line 806, in <module>
    main()
  File "/opt/jumpserver/connect.py", line 753, in main
    nav.search()
  File "/opt/jumpserver/connect.py", line 530, in search
    color_print(u'[%-3s] %-12s %-15s  %-5s  %-10s  %s' % ('ID', u'主机名', 'IP', u'端口', u'系统用户', u'备注'), 'title')
  File "/opt/jumpserver/connect.py", line 58, in color_print
    print msg
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-16: ordinal not in range(128)
 
```

**Comment by eshujiushiwo** [comment]
解决了。
把connect.py中530行的

```
u'主机名', 'IP', u'端口', u'系统用户', u'备注'
```
u都去掉就可以了。

**Comment by ibuler** [comment]
已经都去掉，请pull一下测试

**Comment by eshujiushiwo** [comment]
好的。
已经确认，生效了。
感谢
